templates4 = Template.create([{ title: 'Third World Success Kid', path: '265j.jpg' },
	{ title: 'Bad Luck Brian', path: '1bip.jpg' },
	{ title: 'Third World Skeptical Kid', path: '265k.jpg'},
	{ title: 'Batman Slapping Robin', path: '9ehk.jpg'},
	{ title: 'That Would Be Great', path: 'c2qn.jpg'},
	{ title: 'Yao Ming', path: '2c47.jpg'},
	{ title: "Didn't You Squidward", path: '26br.jpg'},
	{ title: 'Drunk Baby', path: '25w0.jpg'},
	{ title: 'Dwight Schrute', path: '1bhu.jpg'},
	{ title: 'Baby Godfather', path: '26h4.jpg'},
	{ title: 'Bear Grylls (Better Drink My Own Piss)', path: '1bho.jpg'},
	{ title: 'Impossibru Guy', path: '6l71.jpg'},
	{ title: 'Advice Mallard', path: 't2sg.jpg'},
	{ title: 'Lazy College Senior', path: '26a2.jpg'},
	{ title: 'Ron Burgundy', path: 'qeqb.jpg'},
	{ title: 'Most Interesting Cat In The World', path: '1bic.jpg'},
	{ title: 'Bad Luck Bear', path: '5wnr.jpg'},
	{ title: 'Friend Zone Fiona', path: '264v.jpg'},
	{ title: 'Stoner Dog', path: 'stoner-dog-meme-template.jpg'},
	{ title: 'College Freshman', path: '2543c.jpg'}
	]);